'''Global constants'''

# SCREEN SIZE
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

# FONT
FONT_YUN = 'res/Yun_16x16_sm.png'
FONT_TAFFER20 = 'res/Taffer_20x20.png'
FONT_TAFFER = 'res/Taffer_10x10.png'
FONT_CHEEPICUS = 'res/Cheepicus_16x16.png'

FONT = FONT_TAFFER

# MAP
MAP_WIDTH = 80
MAP_HEIGHT = 50

MAP_ROOM_MIN_SIZE = 4
MAP_ROOM_MAX_SIZE = 10
MAP_ROOM_MAX_ROOMS = 30

MAP_MAX_FAILURES = 1000

# LAYERS
LAYER_BACKGROUND = 0
LAYER_GROUND = 1
LAYER_BLOCKING = 2

# RENDER
FOV = True
CALC_LOS = True
